Repository DanBot-Hosting/DanBotHostingStats, pull requests merged in 2023-09, with the labels that each got.

#405 chore: removing console log
  bot/discord/commands/user/link.js
Labels: Chore

#406 feat: removing ANOTHER useless global variable
  index.js
Labels: Enhancement, Awaiting Team Approval

#413 feat: poll ping command
  bot/discord/commands/staff/pollping.js
  index.js
Labels: New Feature
