Repository DanBot-Hosting/DanBotHostingStats, pull requests merged in 2023-08, with the labels that each got.

#370 Remove vc command and code relating to it.
  bot/discord/commands/help.js
  bot/discord/commands/vc.js
  bot/discord/events/voiceStateUpdate.js
Labels: enhancement

#371 Cleanout
  bot/discord/commands/help.js
  bot/discord/commands/reload.js
  index.js
  util/MBL.js
  util/arc-sw.js
  util/discordAPI.js
  util/isSnowflake.js
  util/pterodactyl.js
Labels: enhancement

#372 Update docs.js
  bot/discord/commands/server/docs.js
Labels: enhancement

#374 Java egg update.
  create-free/java.js
  create-premium/java.js
Labels: enhancement

#376 feat: adding grafana egg + slight change to beta command.
  bot/discord/commands/server/create-beta.js
  bot/discord/commands/server/create-donator.js
  bot/discord/commands/server/create.js
  bot/discord/commands/server/docs.js
  create-free/grafana.js
  create-premium/grafana.js
  createData.js
  createData_Prem.js
Labels: Enhancement

#380 Enhancements to "nodestatschecker" file.
  nodestatsChecker.js
Labels: Enhancement, Awaiting Team Approval

#387 chore: various small changes
  bot/discord/commands/staff/update.js
  bot/discord/events/message.js
  bot/discord/events/messageUpdate.js
  bot/discord/events/ready.js
  bot/discord/util/cap.js
  index.js
Labels: Enhancement, Awaiting Team Approval, New Feature

#392 chore: adding developers to readme
  README.md
Labels: Awaiting Team Approval, Chore

#382 Cleaning out some big files slowly.
  bot/discord/events/message.js
  bot/discord/events/ready.js
  index.js
Labels: Enhancement, Help Wanted

#395 feat: error caching
  bot/discord/events/ready.js
Labels: Enhancement, Awaiting Team Approval

#396 possibly fix server delete
  bot/discord/commands/server/delete.js
Labels: Bug, Enhancement, Awaiting Team Approval

#400 Disabling Panel Commands.
  bot/discord/commands/server/create-donator.js
  bot/discord/commands/server/create.js
  bot/discord/commands/server/delete.js
Labels: Bug, Approval Skipped

#401 feat: slight change
  nodestatsChecker.js
Labels: Chore, Approval Skipped

#399 feat(server/list): group servers by type
  bot/discord/commands/server/list.js
Labels: Enhancement, Awaiting Team Approval

#402 Attempt to debug server list.
  bot/discord/commands/server/list.js
Labels: Bug, Awaiting Team Approval

#403 feat: message publishing
  bot/discord/events/message.js
Labels: Enhancement, Awaiting Team Approval, New Feature
