Repository DanBot-Hosting/DanBotHostingStats, pull requests merged in 2024-07, with the labels that each got.

#437 refactor!: cleaning up server count
  bot/discord/commands/server/count.js
Labels: enhancement, refractor

#436 chore: Fix staff proxyfix
  bot/discord/commands/staff/proxyfix.js
Labels: enhancement

#438 refractor!: removing hardcoded ids from the lockdown command
  bot/discord/commands/staff/lockdown.js
  example-config.json
  generate-example-config.js
  package.json
Labels: awaiting team approval, refractor

#439 chore: changing variable name to be logical
  bot/discord/commands/server/create-donator.js
  bot/discord/commands/server/redeem.js
  bot/discord/commands/user/premium.js
  example-config.json
Labels: awaiting team approval, chore

#440 refractor: getting rid of the message reaction add items
  bot/discord/events/raw.js
  bot/discord/events/reactionAdd.js
  bot/discord/events/reactionRemove.js
  bot/discord/reactionRoles.js
  example-config.json
Labels: awaiting team approval, chore, refractor

#442 refractor!: some QoL changes
  bot/discord/commands/user/help.js
  bot/discord/commands/user/invites.js
  bot/discord/commands/user/password.js
  bot/discord/commands/user/premium.js
  bot/discord/commands/user/unlink.js
  bot/discord/util/cap.js
  bot/discord/util/generatePassword.js
Labels: awaiting team approval, refractor
