Repository DanBot-Hosting/DanBotHostingStats, pull requests merged in 2025-03, with the labels that each got.

#489 Fixed donator role assign code and some bugs
  src/commands/staff/premium.js
Labels: bug

#490 feat: new helper commands
  src/commands/staff/deletekey.js
  src/commands/staff/drop.js
Labels: enhancement, new feature, refactor

#491 fix!: bug where the interaction was not handled
  src/commands/user/delete.js
Labels: enhancement, awaiting team approval

#492 fix!(unproxy): handles down servers
  src/commands/server/unproxy.js
Labels: bug, awaiting team approval

#493 fix!(proxy): returning a response when timeout
  src/commands/server/proxy.js
Labels: bug, chore
